#!/bin/bash
# make_boards.sh <final tag> : hair pass Q boards (S = h51a start, X = final; locked m2 + M_SlightArch package, same session / lights)
set -u; cd "/c/Users/berat/OneDrive/Documents/Unreal Projects/ActionAdventureMovementS"; t=${1:?tag}; PY="/c/Program Files/Epic Games/UE_5.8/Engine/Binaries/ThirdParty/Python3/Win64/python.exe"; LB=Tools/CharacterLookdev_20260930/lk_board.py
QD=Saved/Codex/GD11_HairQ_20261006; Q="$(cygpath -w "$(pwd)/$QD")"; B="$Q\\public_report\\boards"; PV="$Q\\pv"; R6="$Q\\reference\\REF_6VIEW_user_20261006.png"; RF="$(cygpath -w "$(pwd)/Saved/Codex/GD11_HeadRefinementO_20261005/reference/temiz_kirpimlar")"; mkdir -p $QD/public_report/boards
pt() { "$PY" -c "import json; d=json.load(open('$QD/prov/$1.json')); print(d['read_at'][11:16])" 2>/dev/null || echo "--:--"; }
SL="h51a prov $(pt g11rqS)"; FL="$t prov $(pt g11rqX)"
"$PY" $LB "$B\\01_REF_START_NEW.jpg" "GD11 hair Q - 01 reference (user 6-view sheet + original crops) | start h51a | new $t. Front and two 3/4; studio light; m2 + M DNA + M_SlightArch + k10/e2 locked" 520 "$R6|user 6-view reference (target of this pass), $RF\\REF_01_ON_YUZ.png|original front, $RF\\REF_02_ORIJINAL_3Q.png|original 3/4" "g11rqS_front_custom.png|front - $SL, g11rqS_q3L_custom.png|3/4 L - h51a, g11rqS_q3R_custom.png|3/4 R - h51a" "g11rqX_front_custom.png|front - $FL, g11rqX_q3L_custom.png|3/4 L - $t, g11rqX_q3R_custom.png|3/4 R - $t"
"$PY" $LB "$B\\02_FRONT_HAIR_SHAPE.jpg" "GD11 hair Q - 02 front hair shape / top mass: h51a (row 1) vs $t (row 2): front, top view, face-front close, front main only" 460 "g11rqS_front_custom.png|h51a front, g11rqS_top_main_custom.png|h51a top (main), g11rqS_fcfront_custom.png|h51a face front, g11rqS_front_main_custom.png|h51a front main" "g11rqX_front_custom.png|$t front, g11rqX_top_main_custom.png|$t top (main), g11rqX_fcfront_custom.png|$t face front, g11rqX_front_main_custom.png|$t front main"
"$PY" $LB "$B\\03_TEMPLE_SIDE.jpg" "GD11 hair Q - 03 temple / side coverage, both sides: temple close (studio), 3/4 main only and full; h51a vs $t" 440 "g11rqS_tmR_custom.png|h51a temple R, g11rqX_tmR_custom.png|$t temple R, g11rqS_tmL_custom.png|h51a temple L, g11rqX_tmL_custom.png|$t temple L" "g11rqS_q3R_main_custom.png|h51a 3/4 R main, g11rqX_q3R_main_custom.png|$t 3/4 R main, g11rqS_q3L_main_custom.png|h51a 3/4 L main, g11rqX_q3L_main_custom.png|$t 3/4 L main" "g11rqS_profRlit_custom.png|h51a profile R, g11rqX_profRlit_custom.png|$t profile R, g11rqS_profLlit_custom.png|h51a profile L, g11rqX_profLlit_custom.png|$t profile L"
"$PY" $LB "$B\\04_NAPE_LONG_HAIR.jpg" "GD11 hair Q - 04 nape long hair: MAIN only (row 1) and full hair (row 2), back / nape close / rear 3/4 (rear-lit), h51a vs $t; row 3 strand geometry of $t: long nape hair joining the bun only (orange) and the hanging loose layer (grey)" 440 "g11rqS_back_main_custom.png|h51a back main, g11rqX_back_main_custom.png|$t back main, g11rqS_napeB_main_custom.png|h51a nape main, g11rqX_napeB_main_custom.png|$t nape main" "g11rqS_back_custom.png|h51a back full, g11rqX_back_custom.png|$t back full, g11rqS_napeB_custom.png|h51a nape full, g11rqX_napeB_custom.png|$t nape full" "$PV\\tagA_$t.png|$t long nape hair joining the bun, $PV\\tagM_$t.png|$t hanging / messy loose layer"
"$PY" $LB "$B\\05_UNDER_BUN.jpg" "GD11 hair Q - 05 under-bun connection: back + two rear 3/4 (rear-lit) and bun close; h51a (row 1) vs $t (row 2); row 3 $t main only" 440 "g11rqS_back_custom.png|h51a back, g11rqS_rear3qR_custom.png|h51a rear 3/4 R, g11rqS_rear3qL_custom.png|h51a rear 3/4 L, g11rqS_bunR_custom.png|h51a bun R" "g11rqX_back_custom.png|$t back, g11rqX_rear3qR_custom.png|$t rear 3/4 R, g11rqX_rear3qL_custom.png|$t rear 3/4 L, g11rqX_bunR_custom.png|$t bun R" "g11rqX_back_main_custom.png|$t back main, g11rqX_rear3qR_main_custom.png|$t rear 3/4 R main, g11rqX_rear3qL_main_custom.png|$t rear 3/4 L main, g11rqX_bunL_main_custom.png|$t bun L main"
"$PY" $LB "$B\\06_GUIDES.jpg" "GD11 hair Q - 06 main lock centrelines before (h51a) / after ($t, q4 authored), coloured by family (red A front edge, orange B front top, green C temple edge, cyan D above ear, blue E upper side, pink F top mid, yellow G behind ear, grey H back / crown kept)" 700 "$PV\\guides_h51a.png|BEFORE h51a" "$PV\\guides_q4.png|AFTER $t"
"$PY" $LB "$B\\07_UNREAL_FINAL.jpg" "GD11 hair Q - 07 Unreal final $t (same six views as the user reference): front, 3/4 L, 3/4 R, profile L, back, profile R; row 2 main only; row 3 technical (pitch, turns, run-stop)" 420 "g11rqX_front_custom.png|front, g11rqX_q3L_custom.png|3/4 L, g11rqX_q3R_custom.png|3/4 R, g11rqX_profL_custom.png|profile L, g11rqX_back_custom.png|back, g11rqX_profRlit_custom.png|profile R" "g11rqX_front_main_custom.png|front main, g11rqX_q3L_main_custom.png|3/4 L main, g11rqX_q3R_main_custom.png|3/4 R main, g11rqX_profL_main_custom.png|profile L main, g11rqX_back_main_custom.png|back main, g11rqX_profR_main_custom.png|profile R main" "g11rqP_pitchUp_side_custom.png|pitch up, g11rqP_pitchDn_side_custom.png|pitch down, g11rqmot_turnL06_q3_custom.png|turn L, g11rqmot_turnR12_back_custom.png|turn R back, g11rqmot_stop06_back_custom.png|run-stop back, g11rqmot_look85_front_custom.png|look 85"
ls -la $QD/public_report/boards
