#!/bin/bash
# make_boards.sh <final tag> : hair pass P report boards (S = h51a start, F = final; both on the locked m2 + M_SlightArch package, same session / lights)
set -u; cd "/c/Users/berat/OneDrive/Documents/Unreal Projects/ActionAdventureMovementS"; t=${1:?tag}; PY="/c/Program Files/Epic Games/UE_5.8/Engine/Binaries/ThirdParty/Python3/Win64/python.exe"; LB=Tools/CharacterLookdev_20260930/lk_board.py
PD=Saved/Codex/GD11_HairP_20261006; P="$(cygpath -w "$(pwd)/$PD")"; B="$P\\public_report\\boards"; PV="$P\\pv"; RF="$(cygpath -w "$(pwd)/Saved/Codex/GD11_HeadRefinementO_20261005/reference/temiz_kirpimlar")"; TR="$(cygpath -w "$(pwd)/Saved/Codex/CharacterIdentity_20260930/track")"; mkdir -p $PD/public_report/boards
pt() { "$PY" -c "import json; d=json.load(open('$PD/prov/$1.json')); print(d['read_at'][11:16])" 2>/dev/null || echo "--:--"; }
SL="S h51a prov $(pt g11rpS)"; FL="F $t prov $(pt g11rpF)"
"$PY" $LB "$B\\01_REF_START_NEW.jpg" "GD11 hair P - 01 reference | start h51a | new $t (m2 + M DNA + M_SlightArch + k10/e2 locked). Front and two 3/4, studio light, full hair" 520 "$RF\\REF_01_ON_YUZ.png|reference front, $RF\\REF_02_ORIJINAL_3Q.png|reference 3/4, $RF\\REF_03_PROFIL_YALNIZ_YARDIMCI.png|reference profile (helper)" "g11rpS_front_custom.png|front - $SL, g11rpS_q3R_custom.png|3/4 R - h51a, g11rpS_q3L_custom.png|3/4 L - h51a, g11rpS_profR_custom.png|profile - h51a" "g11rpF_front_custom.png|front - $FL, g11rpF_q3R_custom.png|3/4 R - $t, g11rpF_q3L_custom.png|3/4 L - $t, g11rpF_profR_custom.png|profile - $t"
"$PY" $LB "$B\\02_MAIN_FLOW.jpg" "GD11 hair P - 02 MAIN groom only (loose / face-frame / wisps hidden): h51a (row 1) vs $t (row 2); row 3 lock strands by builder group (strand geometry) h51a vs $t" 460 "g11rpS_front_main_custom.png|h51a front, g11rpS_q3R_main_custom.png|h51a 3/4 R, g11rpS_q3L_main_custom.png|h51a 3/4 L, g11rpS_profR_main_custom.png|h51a profile, g11rpS_top_main_custom.png|h51a top" "g11rpF_front_main_custom.png|$t front, g11rpF_q3R_main_custom.png|$t 3/4 R, g11rpF_q3L_main_custom.png|$t 3/4 L, g11rpF_profR_main_custom.png|$t profile, g11rpF_top_main_custom.png|$t top" "$PV\\tagLocks_h51a.png|h51a lock strands front / 3-4 / profile / rear / back, $PV\\tagLocks_$t.png|$t lock strands"
"$PY" $LB "$B\\03_TEMPLE_SIDE.jpg" "GD11 hair P - 03 temple and side coverage: close (studio) + whole head; h51a vs $t; full hair and main only" 460 "g11rpS_tmR_custom.png|h51a temple R, g11rpF_tmR_custom.png|$t temple R, g11rpS_tmL_custom.png|h51a temple L, g11rpF_tmL_custom.png|$t temple L" "g11rpS_tmR_main_custom.png|h51a temple R main, g11rpF_tmR_main_custom.png|$t temple R main, g11rpS_q3R_main_custom.png|h51a 3/4 main, g11rpF_q3R_main_custom.png|$t 3/4 main" "g11rpS_fcq3_custom.png|h51a face 3/4, g11rpF_fcq3_custom.png|$t face 3/4, g11rpS_fcfront_custom.png|h51a face front, g11rpF_fcfront_custom.png|$t face front"
"$PY" $LB "$B\\04_EAR.jpg" "GD11 hair P - 04 above / behind the ear, both sides (rear-lit profiles, closer ear views); h51a vs $t; full and main only" 460 "g11rpS_profRlit_custom.png|h51a profile R lit, g11rpF_profRlit_custom.png|$t profile R lit, g11rpS_profLlit_custom.png|h51a profile L lit, g11rpF_profLlit_custom.png|$t profile L lit" "g11rpS_earR_custom.png|h51a ear R, g11rpF_earR_custom.png|$t ear R, g11rpS_earL_custom.png|h51a ear L, g11rpF_earL_custom.png|$t ear L" "g11rpS_earR_main_custom.png|h51a ear R main, g11rpF_earR_main_custom.png|$t ear R main, g11rpS_earL_main_custom.png|h51a ear L main, g11rpF_earL_main_custom.png|$t ear L main"
"$PY" $LB "$B\\05_NAPE.jpg" "GD11 hair P - 05 nape: back and nape close (rear-lit), full hair and main only; row 3 strand geometry: only the long nape hair joining the bun (A) | free (B) | wisps (C) for $t" 460 "g11rpS_back_custom.png|h51a back, g11rpF_back_custom.png|$t back, g11rpS_napeB_custom.png|h51a nape, g11rpF_napeB_custom.png|$t nape" "g11rpS_back_main_custom.png|h51a back main, g11rpF_back_main_custom.png|$t back main, g11rpS_napeB_main_custom.png|h51a nape main, g11rpF_napeB_main_custom.png|$t nape main" "$PV\\tagA_$t.png|A nape join $t, $PV\\tagB_$t.png|B nape free $t, $PV\\tagC_$t.png|C nape wisps $t"
"$PY" $LB "$B\\06_BUN.jpg" "GD11 hair P - 06 bun joins: back + two rear 3/4 (rear-lit) and closer bun views; h51a vs $t" 460 "g11rpS_rear3qR_custom.png|h51a rear 3/4 R, g11rpF_rear3qR_custom.png|$t rear 3/4 R, g11rpS_rear3qL_custom.png|h51a rear 3/4 L, g11rpF_rear3qL_custom.png|$t rear 3/4 L" "g11rpS_bunR_custom.png|h51a bun R, g11rpF_bunR_custom.png|$t bun R, g11rpS_bunL_custom.png|h51a bun L, g11rpF_bunL_custom.png|$t bun L" "g11rpS_rear3qR_main_custom.png|h51a rear 3/4 main, g11rpF_rear3qR_main_custom.png|$t rear 3/4 main, g11rpS_back_main_custom.png|h51a back main, g11rpF_back_main_custom.png|$t back main"
"$PY" $LB "$B\\07_GUIDES.jpg" "GD11 hair P - 07 main lock centrelines (prim:*) before (h51a) and after ($t), coloured by the pass-P family (red A front edge, orange B front top, green C temple edge, cyan D above ear, blue E upper side, pink F top mid, yellow G behind ear, grey H back); views front, 3/4 L, 3/4 R, profile L, profile R, rear 3/4, back" 700 "$PV\\guides_h51a.png|BEFORE h51a (same roots, coloured by the new family)" "$PV\\guides_p4.png|AFTER $t authored centrelines"
"$PY" $LB "$B\\08_UNREAL_FINAL.jpg" "GD11 hair P - 08 Unreal final $t on the locked face package: front, 3/4, profile, back (studio / rear-lit); row 2 technical: head pitch up / down, turns and run-stop" 500 "g11rpF_front_custom.png|front, g11rpF_q3R_custom.png|3/4 R, g11rpF_q3L_custom.png|3/4 L, g11rpF_profR_custom.png|profile, g11rpF_back_custom.png|back" "g11rpP_pitchUp_side_custom.png|pitch up, g11rpP_pitchDn_side_custom.png|pitch down, g11rpmot_turnL06_q3_custom.png|turn L, g11rpmot_look85_front_custom.png|look 85, g11rpmot_stop06_back_custom.png|run-stop back"
ls -la $PD/public_report/boards
