#!/bin/bash
# make_boards.sh <face o?> <hair h??> <brow b?> : O report boards. S = n1+h49a+M_Fine (N record, start), NO = nose only (o?+h49a+M_Fine), BO = brow only (n1+h49a+custom brow),
# HO = hair only (n1+h??+M_Fine), C = o?+h??+custom brow. All UE captures carry editor-read provenance (prov/<label>.json).
set -u; cd "/c/Users/berat/OneDrive/Documents/Unreal Projects/ActionAdventureMovementS"; f=${1:?face}; t=${2:?hair}; bt=${3:?brow}; PY="/c/Program Files/Epic Games/UE_5.8/Engine/Binaries/ThirdParty/Python3/Win64/python.exe"; LB=Tools/CharacterLookdev_20260930/lk_board.py
OD=Saved/Codex/GD11_HeadRefinementO_20261005; O="$(cygpath -w "$(pwd)/$OD")"; B="$O\\public_report\\boards"; PV="$O\\pv"; RF="$O\\reference\\temiz_kirpimlar"; TR="$(cygpath -w "$(pwd)/Saved/Codex/CharacterIdentity_20260930/track")"; mkdir -p $OD/public_report/boards
pt() { "$PY" -c "import json; d=json.load(open('$OD/prov/$1.json')); print(d['read_at'][11:16])" 2>/dev/null || echo "--:--"; }
SL="S n1+h49a+M_Fine prov $(pt g11roS)"; NL="NO $f+h49a+M_Fine prov $(pt g11roNO)"; BL="BO n1+h49a+brow $bt prov $(pt g11roBO)"; HL="HO n1+$t+M_Fine prov $(pt g11roHO)"; CL="C $f+$t+brow $bt prov $(pt g11roC)"
V5="front q3L q3R profL profR"; row() { p=$1; l=$2; out=""; for v in $V5; do out="$out${p}_${v}_custom.png|$v - $l, "; done; echo "${out%, }"; }
"$PY" $LB "$B\\01_WHOLE_HEAD.jpg" "GD11 O - 01 whole head: user reference (row 1) | start S = N record n1+h49a+M_Fine (row 2) | combined C = $f+$t+brow $bt (row 3). Same cameras, studio light, neutral rig" 500 "$TR\\ref_front_x4.png|reference front, $TR\\ref_q3L_x4.png|reference 3/4 L, $TR\\ref_q3R_x4.png|reference 3/4 R, $TR\\ref_profL_x4.png|reference profile L, $TR\\ref_profR_x4.png|reference profile R" "$(row g11roS "$SL")" "$(row g11roC "$CL")"
"$PY" $LB "$B\\02_NOSE_TIP.jpg" "GD11 O - 02 nose tip / alae: n1 (start) vs $f on the SAME h49a + M_Fine. Row 1 front close, row 2 matched 3/4 R + L, row 3 profile + from below (nostrils / columella), row 4 reference nose crops + clay from below n1 / $f + displacement heat" 520 "g11roSfc_studio_fcfront_custom.png|n1 front - $SL, g11roNOfc_studio_fcfront_custom.png|$f front - $NL, g11roSn_studio_nosefront_custom.png|n1 nose front, g11roNOn_studio_nosefront_custom.png|$f nose front" "g11roSfc_studio_fcq3_custom.png|n1 3/4 R, g11roNOfc_studio_fcq3_custom.png|$f 3/4 R, g11roSn_studio_fcq3L_custom.png|n1 3/4 L, g11roNOn_studio_fcq3L_custom.png|$f 3/4 L" "g11roSfc_studio_fcprofR_custom.png|n1 profile, g11roNOfc_studio_fcprofR_custom.png|$f profile, g11roSn_studio_noselow_custom.png|n1 from below, g11roNOn_studio_noselow_custom.png|$f from below" "$RF\\REF_04_BURUN_ON.png|reference nose front (user crop), $RF\\REF_05_BURUN_3Q.png|reference nose 3/4 (user crop), $PV\\clay_n1_o${f#o}\\head_N1_low3q.png|clay n1 from below, $PV\\clay_n1_o${f#o}\\head_O${f#o}_low3q.png|clay $f from below, $PV\\heat_O${f#o}_front.png|heat $f vs n1 (2 mm red)"
"$PY" $LB "$B\\03_BROW.jpg" "GD11 O - 03 brow on the SAME n1 + h49a: reference | rejected M_Fine (S) | custom brow $bt (BO). Row 1 front close (studio), row 2 3/4 (studio), row 3 brow close-ups and the brow design iterations b1 / b2 / $bt" 520 "$RF\\REF_06_KAS_ON.png|reference brow front (user crop), g11roSfc_studio_fcfront_custom.png|M_Fine (rejected) - $SL, g11roBOfc_studio_fcfront_custom.png|custom brow $bt - $BL" "$RF\\REF_07_KAS_3Q.png|reference brow 3/4 (user crop), g11roSfc_studio_fcq3_custom.png|M_Fine 3/4, g11roBOfc_studio_fcq3_custom.png|custom brow $bt 3/4" "g11roB1_studio_browfront_custom.png|b1 - too high thin orange, g11roBb2d_studio_browfront_custom.png|b2 dark material - too black and solid, g11roB${bt}_studio_browfront_custom.png|$bt front close, g11roB${bt}_studio_brow3q_custom.png|$bt 3/4 close"
"$PY" $LB "$B\\04_MAIN_HAIR_FLOW.jpg" "GD11 O - 04 main hair flow and head coverage with the LOOSE groom HIDDEN (only the main mass): h49a (start) vs $t on n1. Row 3: full hair (loose shown). Row 4: user hair panel crops" 480 "g11roSmo_mo_front_custom.png|h49a main front, g11roHOmo_mo_front_custom.png|$t main front, g11roSmo_mo_q3R_custom.png|h49a main 3/4 R, g11roHOmo_mo_q3R_custom.png|$t main 3/4 R, g11roSmo_mo_profR_custom.png|h49a main profile, g11roHOmo_mo_profR_custom.png|$t main profile" "g11roSmo_mo_q3L_custom.png|h49a main 3/4 L, g11roHOmo_mo_q3L_custom.png|$t main 3/4 L, g11roSmo_mo_profL_custom.png|h49a main profile L, g11roHOmo_mo_profL_custom.png|$t main profile L, g11roSmo_mo_profR_lit_custom.png|h49a main profile rear-lit, g11roHOmo_mo_profR_lit_custom.png|$t main profile rear-lit" "g11roS_front_custom.png|h49a full front - $SL, g11roHO_front_custom.png|$t full front - $HL, g11roS_q3R_custom.png|h49a full 3/4 R, g11roHO_q3R_custom.png|$t full 3/4 R, g11roS_profR_custom.png|h49a full profile, g11roHO_profR_custom.png|$t full profile" "$RF\\REF_02_ORIJINAL_3Q.png|reference 3/4 (user crop), $RF\\REF_03_PROFIL_YALNIZ_YARDIMCI.png|reference profile (helper only), $PV\\tagE_h49a.png|h49a front+side main groups (strand geometry), $PV\\tagE_${t}.png|$t front+side main groups (strand geometry)"
"$PY" $LB "$B\\05_NAPE_EAR_BUN.jpg" "GD11 O - 05 nape / behind-ear / bun: back, rear 3/4 R + L, profile; main only (loose hidden) vs full; h49a vs $t on n1. Row 4: tag groups A join / B free / C wisp (strand geometry)" 480 "g11roSmo_mo_back_custom.png|h49a main back, g11roHOmo_mo_back_custom.png|$t main back, g11roSmo_mo_rear3qR_custom.png|h49a main rear 3/4 R, g11roHOmo_mo_rear3qR_custom.png|$t main rear 3/4 R, g11roSmo_mo_rear3qL_custom.png|h49a main rear 3/4 L, g11roHOmo_mo_rear3qL_custom.png|$t main rear 3/4 L" "g11roSmo_mo_rear3qR_lit_custom.png|h49a main rear 3/4 rear-lit, g11roHOmo_mo_rear3qR_lit_custom.png|$t main rear 3/4 rear-lit, g11roS_back_custom.png|h49a full back - $SL, g11roHO_back_custom.png|$t full back - $HL, g11roS_rear3qR_custom.png|h49a full rear 3/4, g11roHO_rear3qR_custom.png|$t full rear 3/4" "$PV\\tagA_${t}.png|A nape join ($t), $PV\\tagB_${t}.png|B nape free ($t), $PV\\tagC_${t}.png|C nape wisp ($t), $PV\\tagD_${t}.png|D side+back to bun ($t)"
"$PY" $LB "$B\\06_SEPARATION.jpg" "GD11 O - 06 separation (front / 3/4 R / front close): start S | nose only NO | brow only BO | hair only HO | combined C; studio light. Row 4: gameplay light (sun + sky) S vs C" 460 "g11roS_front_custom.png|S - $SL, g11roNO_front_custom.png|NO - $NL, g11roBO_front_custom.png|BO - $BL, g11roHO_front_custom.png|HO - $HL, g11roC_front_custom.png|C - $CL" "g11roS_q3R_custom.png|S 3/4, g11roNO_q3R_custom.png|NO 3/4, g11roBO_q3R_custom.png|BO 3/4, g11roHO_q3R_custom.png|HO 3/4, g11roC_q3R_custom.png|C 3/4" "g11roSfc_studio_fcfront_custom.png|S close, g11roNOfc_studio_fcfront_custom.png|NO close, g11roBOfc_studio_fcfront_custom.png|BO close, g11roHOfc_studio_fcfront_custom.png|HO close, g11roCfc_studio_fcfront_custom.png|C close" "g11roSgp_gp_front_custom.png|S gameplay front, g11roCgp_gp_front_custom.png|C gameplay front, g11roSgp_gp_q3R_custom.png|S gameplay 3/4, g11roCgp_gp_q3R_custom.png|C gameplay 3/4, g11roCgp_gp_fcq3_custom.png|C gameplay close 3/4"
"$PY" $LB "$B\\07_TECH_REOPEN.jpg" "GD11 O - 07 technical (combined C): rig poses (blink / brow / gaze / jaw / smile / mouth open), head turns and pitch, run-stop motion, LOD distance row, after editor restart + reopen" 420 "g11rorig_blink_front_custom.png|blink, g11rorig_brows_up_front_custom.png|brows up, g11rorig_look_left_front_custom.png|look left, g11rorig_jaw_open_front_custom.png|jaw open, g11rorig_smile_front_custom.png|smile, g11rorig_nostril_dilate_front_custom.png|nostril dilate" "g11roRL_rlL_front_full_custom.png|turn L, g11roRL_rlR_front_full_custom.png|turn R, g11roP_pitchUp_side_custom.png|pitch up, g11roP_pitchDn_side_custom.png|pitch down, g11romot_turnL06_q3_custom.png|turn L 0.6s, g11romot_stop06_front_custom.png|stop 0.6s" "g11rolod_f_125_custom.png|LOD 125 cm, g11rolod_f_300_custom.png|300 cm, g11rolod_f_600_custom.png|600 cm, g11rolod_f_1200_custom.png|1200 cm, g11rolod_d_600_custom.png|600 cm diag, g11rolod_b_600_custom.png|600 cm back" "g11roafter_front_custom.png|after restart front, g11roafter_q3R_custom.png|after restart 3/4, g11roafter_profR_custom.png|after restart profile, g11roafter_back_custom.png|after restart back, g11roafter_profR_lit_custom.png|after restart profile rear-lit"
ls -la $OD/public_report/boards
