#!/bin/bash
# make_boards.sh : M report boards. S = F4ab+h47a (start), FO = m2+h47a (face only), HO = F4ab+h48a (hair only), C = m2+h48a (combined). Labels carry the editor-read provenance time.
set -u; cd "/c/Users/berat/OneDrive/Documents/Unreal Projects/ActionAdventureMovementS"; PY="/c/Program Files/Epic Games/UE_5.8/Engine/Binaries/ThirdParty/Python3/Win64/python.exe"; LB=Tools/CharacterLookdev_20260930/lk_board.py
M="$(cygpath -w "$(pwd)/Saved/Codex/GD11_HeadRefinementM_20261005")"; TR="$(cygpath -w "$(pwd)/Saved/Codex/CharacterIdentity_20260930/track")"; B="$M\\public_report\\boards"; PV="$M\\pv"; CL="$M\\pv\\clay"; PN="$M\\pv\\panel"; FR="$M\\frames"
pt() { "$PY" -c "import json; d=json.load(open('Saved/Codex/GD11_HeadRefinementM_20261005/prov/$1.json')); print(d['read_at'][11:16])"; }
S=g11rmS; SL="S F4ab+h47a prov $(pt g11rmS)"; FO=g11rmFO; FL="FO m2+h47a prov $(pt g11rmFO)"; HO=g11rmHO; HL="HO F4ab+h48a prov $(pt g11rmHO)"; C=g11rmC; CLB="C m2+h48a prov $(pt g11rmC)"
V7="front q3L q3R profL profR rear3qR back"; row() { p=$1; l=$2; out=""; for v in $V7; do out="$out${p}_${v}_custom.png|$v - $l, "; done; echo "${out%, }"; }
"$PY" $LB "$B\\01_FACE_START_VS_NEW.jpg" "GD11 M - 01 face: start F4ab (row 1) vs new face m2 (row 2), SAME hair h47a, same k10, same cameras/studio light/neutral rig. Row 3: reference frames - F4ab vs m2 real render in the solved reference cameras + 50% overlay" 480 "$(row $S "$SL")" "$(row $FO "$FL")" "$FR\\g11rmf4ab_real_F.png|F4ab in reference front frame, $FR\\g11rm2_real_F.png|m2 in reference front frame, $FR\\g11rm2_ovF.png|m2 50% overlay on reference, $FR\\g11rmf4ab_real_C.png|F4ab reference 3/4 frame, $FR\\g11rm2_real_C.png|m2 reference 3/4 frame, $TR\\ref_front_x4.png|reference front, $TR\\ref_close_x2.png|reference 3/4"
"$PY" $LB "$B\\02_HAIR_START_VS_NEW.jpg" "GD11 M - 02 hair: h47a (row 1) vs h48a (row 2) on the SAME unchanged F4ab + k10; row 3: rear light sets" 480 "$(row $S "$SL")" "$(row $HO "$HL")" "${S}_rear3qR_lit_custom.png|rear 3/4 R lit - $SL, ${HO}_rear3qR_lit_custom.png|rear 3/4 R lit - $HL, ${S}_rear3qL_lit_custom.png|rear 3/4 L lit - $SL, ${HO}_rear3qL_lit_custom.png|rear 3/4 L lit - $HL, ${S}_bun_lit_custom.png|bun - $SL, ${HO}_bun_lit_custom.png|bun - $HL, ${S}_topfront_custom.png|top-front - $SL"
"$PY" $LB "$B\\03_COMBINED_FINAL.jpg" "GD11 M - 03 combined: start F4ab+h47a (row 1) vs final m2+h48a (row 2); row 3: separation front/3-4 R: start | face only | hair only | combined" 480 "$(row $S "$SL")" "$(row $C "$CLB")" "${S}_front_custom.png|start - $SL, ${FO}_front_custom.png|face only - $FL, ${HO}_front_custom.png|hair only - $HL, ${C}_front_custom.png|combined - $CLB, ${S}_q3R_custom.png|start 3/4, ${FO}_q3R_custom.png|face only 3/4, ${C}_q3R_custom.png|combined 3/4"
"$PY" $LB "$B\\04_NOSE_CLOSEUP.jpg" "GD11 M - 04 nose and midface close-ups: start F4ab (h47a) vs new face m2 (h47a). Studio and grazing light; profile; whole face next to each close-up" 560 "g11rmSfc_studio_noseroot_custom.png|nose root studio - $SL, g11rmFOfc_studio_noseroot_custom.png|nose root studio - $FL, g11rmSfc_grazing_noseroot_custom.png|nose root grazing - $SL, g11rmFOfc_grazing_noseroot_custom.png|nose root grazing - $FL, g11rmSfc_studio_midface_custom.png|midface - $SL, g11rmFOfc_studio_midface_custom.png|midface - $FL" "g11rmSfc_studio_fcprofR_custom.png|profile close - $SL, g11rmFOfc_studio_fcprofR_custom.png|profile close - $FL, g11rmSfc_studio_fcq3_custom.png|face 3/4 - $SL, g11rmFOfc_studio_fcq3_custom.png|face 3/4 - $FL, g11rmSfc_studio_fcfront_custom.png|face front - $SL, g11rmFOfc_studio_fcfront_custom.png|face front - $FL" "g11rmSfc_grazing_fcq3_custom.png|face 3/4 grazing - $SL, g11rmFOfc_grazing_fcq3_custom.png|face 3/4 grazing - $FL, g11rmSfc_studio_lips_custom.png|lips-chin - $SL, g11rmFOfc_studio_lips_custom.png|lips-chin - $FL, $CL\\head_F4ab_low3q.png|F4ab clay from below (nostrils), $CL\\head_M2_low3q.png|m2 clay from below"
"$PY" $LB "$B\\05_REAR_HAIR_CLOSEUP.jpg" "GD11 M - 05 nape / behind-ear / under-bun close-ups: h47a vs h48a on F4ab (and combined m2+h48a)" 520 "${S}_cuRear3qR_s_custom.png|nape close R - $SL, ${HO}_cuRear3qR_s_custom.png|nape close R - $HL, ${C}_cuRear3qR_s_custom.png|nape close R - $CLB, ${S}_cuRear3qL_s_custom.png|nape close L - $SL, ${HO}_cuRear3qL_s_custom.png|nape close L - $HL, ${C}_cuRear3qL_s_custom.png|nape close L - $CLB" "${S}_earR_lit_custom.png|ear R rear light - $SL, ${HO}_earR_lit_custom.png|ear R rear light - $HL, ${S}_cuEarR_s_custom.png|ear R - $SL, ${HO}_cuEarR_s_custom.png|ear R - $HL, ${S}_profL_lit_custom.png|profile L rear light - $SL, ${HO}_profL_lit_custom.png|profile L rear light - $HL" "${S}_cuHairline3q_s_custom.png|hairline 3/4 - $SL, ${HO}_cuHairline3q_s_custom.png|hairline 3/4 - $HL, ${S}_cuForehead_s_custom.png|forehead - $SL, ${HO}_cuForehead_s_custom.png|forehead - $HL, ${S}_cuProftop_s_custom.png|crown profile - $SL, ${HO}_cuProftop_s_custom.png|crown profile - $HL" "$PN\\g_h47a_back_nape.png|h47a nape field (strand geometry), $PN\\g_h48a_back_nape.png|h48a nape field (feathered edge), $PN\\g_h47a_rear3qR_full.png|h47a groups rear 3/4, $PN\\g_h48a_rear3qR_full.png|h48a groups rear 3/4, $PN\\g_h47a_profR_loose.png|h47a loose families, $PN\\g_h48a_profR_loose.png|h48a loose families"
"$PY" $LB "$B\\06_PROTECTED_REGIONS.jpg" "GD11 M - 06 face displacement m2 vs F4ab (heat 0..2 mm: grey 0 - yellow 1 - red 2) and clay: lips, philtrum, chin, jaw, eyelids, ears stay below 0.9 mm; cheeks max 1.7 mm" 520 "$PV\\heat_M2_front.png|heat front, $PV\\heat_M2_q3R.png|heat 3/4 R, $PV\\heat_M2_q3L.png|heat 3/4 L, $PV\\heat_M2_profR.png|heat profile R, $PV\\heat_M2_profL.png|heat profile L" "$CL\\head_F4ab_front.png|F4ab clay front, $CL\\head_M2_front.png|m2 clay front, $CL\\head_F4ab_q3R.png|F4ab clay 3/4, $CL\\head_M2_q3R.png|m2 clay 3/4, $CL\\head_F4ab_profR.png|F4ab clay profile, $CL\\head_M2_profR.png|m2 clay profile"
"$PY" $LB "$B\\07_TECHNICAL.jpg" "GD11 M - 07 technical (m2 + h48a, M bindings): rig expressions (hair hidden) - motion - pitch - after clean restart - LOD distance 1.25..25 m" 440 "g11rmrig_neutral_3q_custom.png|neutral, g11rmrig_blink_3q_custom.png|blink, g11rmrig_look_left_3q_custom.png|look L, g11rmrig_brows_up_3q_custom.png|brows up, g11rmrig_smile_3q_custom.png|smile, g11rmrig_lips_closed_3q_custom.png|lips closed, g11rmrig_jaw_open_3q_custom.png|jaw open, g11rmrig_ph_oo_3q_custom.png|viseme oo" "g11rmrig_upper_lip_raise_3q_custom.png|upper lip raise, g11rmrig_sneer_3q_custom.png|sneer, g11rmrig_nostril_dilate_front_custom.png|nostril dilate, g11rmmot_look10_side_custom.png|look 1.0s, g11rmmot_look55_side_custom.png|look 5.5s, g11rmmot_turnL06_back_custom.png|turn L, g11rmmot_stop06_q3_custom.png|stop, g11rmafter_front_custom.png|after restart" "g11rmP_pitchDn_side_custom.png|pitch down, g11rmP_pitchDn_back_custom.png|pitch down back, g11rmP_pitchUp_q3_custom.png|pitch up, g11rmafter_rear3qR_custom.png|after restart rear 3/4, $PN\\lod_f_125.png|front 1.25 m, $PN\\lod_f_600.png|6 m, $PN\\lod_f_1200.png|12 m, $PN\\lod_f_2500.png|25 m"
ls -la "Saved/Codex/GD11_HeadRefinementM_20261005/public_report/boards"
