#!/bin/bash
# make_g11r_boards.sh : GD11 head refinement report boards 01-09 -> Saved/Codex/GD11_HeadRefinement_20261003/public_report/boards
set -u; cd "/c/Users/berat/OneDrive/Documents/Unreal Projects/ActionAdventureMovementS"; R="$(cygpath -m "$PWD")"; C="$R/Saved/Codex/CharacterLookdev_20260930/captures"; K="$R/Saved/Codex/GD11_HeadRefinement_20261003"
F="$K/frames"; TD="$R/Saved/Codex/CharacterIdentity_20260930/track"; O="$K/public_report/boards"; mkdir -p "$O"; G11F="$R/Saved/Codex/CharacterGuardian11_20261002/frames"
PY="/c/Program Files/Epic Games/UE_5.8/Engine/Binaries/ThirdParty/Python3/Win64/python.exe"; B() { "$PY" Tools/CharacterLookdev_20260930/lk_board.py "$O/$1" "$2" "$3" "${@:4}" | tail -c 25; echo; }
c() { echo "$C/$1_custom.png|$2"; }
B 01_GD11_RESTORE.jpg "01 GD11 RESTORE - report frames vs fresh capture of the real GD11 package (no edits)" 430 "$G11F/g4e_real_F.png|GD11 report front, $F/g11base_real_F.png|fresh front, $G11F/g4e_real_C.png|GD11 report 3q, $F/g11base_real_C.png|fresh 3q" "$(c g11base_hair_front 'GD11 h23 front'), $(c g11base_hair_front3q 'GD11 h23 3q'), $(c g11base_hair_side 'GD11 h23 side R'), $(c g11base_hair_back 'GD11 h23 back')"
B 02_FRONT_WHOLE_HEAD.jpg "02 FRONT - REFERENCE | GD11 | face-only change (R3+h23) | NEW candidate (R3+h32)" 470 "$TD/ref_front_x4.png|REFERENCE, $F/g11base_hair_F.png|GD11, $F/g11rr3_hair_F.png|R3 + h23 (face only), $F/g11rh32c_hair_F.png|NEW R3 + h32" "$F/g11base_real_F.png|GD11 no hair, $F/g11rr3_real_F.png|NEW (R3) no hair, $F/g11base_clay_F.png|GD11 clay, $F/g11rr3_clay_F.png|NEW (R3) clay"
B 03_3Q_WHOLE_HEAD.jpg "03 3/4 (re-solved 3/4 camera) - REFERENCE | GD11 | face-only | NEW" 470 "$TD/ref_close_x2.png|REFERENCE, $F/g11base_hair_C.png|GD11, $F/g11rr3_hair_C.png|R3 + h23 (face only), $F/g11rh32c_hair_C.png|NEW R3 + h32" "$F/g11base_real_C.png|GD11 no hair, $F/g11rr3_real_C.png|NEW (R3) no hair, $F/g11base_clay_C.png|GD11 clay, $F/g11rr3_clay_C.png|NEW (R3) clay"
B 04_PROFILES.jpg "04 PROFILES - GD11 | NEW (no hair + clay); generated profile = AUX only" 430 "$(c g11base_cureal_prof_R 'GD11 profile R'), $(c g11rfin_cureal_prof_R 'NEW profile R'), $(c g11base_cureal_prof_L 'GD11 profile L'), $(c g11rfin_cureal_prof_L 'NEW profile L')" "$(c g11base_cuclay_prof_R 'GD11 clay R'), $(c g11rfin_cuclay_prof_R 'NEW clay R'), $(c g11base_cuclay_prof_L 'GD11 clay L'), $(c g11rfin_cuclay_prof_L 'NEW clay L')" "$R/Saved/Codex/CharacterGuardian2_20261001/refB/turnaround_p5.png|AUX generated profile (not authority)"
B 05_NOSE_MOUTH_LOCAL.jpg "05 NOSE / MOUTH / CHEEK local fixes - GD11 (top) vs NEW (bottom), whole face first" 360 "$F/g11base_real_F.png|GD11 whole, $(c g11base_cureal_nose_front 'GD11 nose'), $(c g11base_cureal_nose_3q 'GD11 nose 3q'), $(c g11base2_cureal_nose_below 'GD11 below'), $(c g11base2_cureal_cheek_R80 'GD11 R cheek'), $(c g11base_cureal_mouth_3q 'GD11 mouth')" "$F/g11rr3_real_F.png|NEW whole, $(c g11rr3_cureal_nose_front 'NEW nose'), $(c g11rr3_cureal_nose_3q 'NEW nose 3q'), $(c g11rr3b_cureal_nose_below 'NEW below'), $(c g11rr3b_cureal_cheek_R80 'NEW R cheek'), $(c g11rr3_cureal_mouth_3q 'NEW mouth')"
B 06_EYES_BROWS_EXPRESSION.jpg "06 EYES / BROWS (real iris + groom) - GD11 | NEW ; brow groom test" 470 "$(c g11base_cureal_eyes_front 'GD11 eyes'), $(c g11rfin_cureal_eyes_front 'NEW eyes'), $(c g11base_cureal_eyes_3q 'GD11 eyes 3q'), $(c g11rfin_cureal_eyes_3q 'NEW eyes 3q')" "$(c g11rbrowsa_eyes 'kept: M_SlightArch (GD11)'), $(c g11rbrownat_eyes 'rejected: M_Natural'), $(c g11rbrowsa_front 'kept - face'), $(c g11rbrownat_front 'rejected - face')"
B 07_HAIR.jpg "07 HAIR - GD11 h23 (top) vs NEW h32 (bottom): front / 3q / sides / back / top" 330 "$(c g11base_hair_front 'h23 front'), $(c g11base_hair_front3q 'h23 3q'), $(c g11base_hair_side 'h23 side R'), $(c g11base_hair_side2 'h23 side L'), $(c g11base_hair_back 'h23 back'), $(c g11base_hair_top 'h23 top')" "$(c g11rh32c_hair_front 'h32 front'), $(c g11rh32c_hair_front3q 'h32 3q'), $(c g11rh32c_hair_side 'h32 side R'), $(c g11rh32c_hair_side2 'h32 side L'), $(c g11rh32c_hair_back 'h32 back'), $(c g11rh32c_hair_top 'h32 top')"
B 08_COLOUR_SKIN_NECK.jpg "08 HAIR COLOUR (same geometry) / SKIN k9 / HEAD-NECK - same light" 400 "$TD/ref_close_x2.png|REFERENCE, $F/g11rh32_hair_C.png|h32 (h23 colour), $F/g11rh32c_hair_C.png|h32c (final colour), $F/g11base_real_C.png|GD11 skin k9" "$(c g11base_real_back 'GD11 nape/neck'), $(c g11rafter_real_back 'NEW nape/neck'), $(c g11base_real_side 'GD11 head-neck side'), $(c g11rafter_real_side 'NEW head-neck side')"
B 09_TECHNICAL.jpg "09 TECHNICAL - rig (27 cases incl. sneer/nostrils), LOD, turn/stop, after fresh-editor restart" 260 "$(c g11rfin_rig_neutral_front neutral), $(c g11rfin_rig_blink_front blink), $(c g11rfin_rig_blink_left_front 'blink L'), $(c g11rfin_rig_look_left_front 'look L'), $(c g11rfin_rig_brows_up_front 'brows up'), $(c g11rfin_rig_smile_front smile), $(c g11rfin_rig_jaw_open_front 'jaw open'), $(c g11rfin_rig_ph_mbp_front 'lips closed MBP')" "$(c g11rfin_rig_sneer_front sneer), $(c g11rfin_rig_sneer_3q 'sneer 3q'), $(c g11rfin_rig_upper_lip_raise_front 'upper lip raise'), $(c g11rfin_rig_nostril_dilate_front 'nostril dilate'), $(c g11rfin_rig_ph_ee_front 'viseme EE'), $(c g11rfin_rig_ph_oo_front 'viseme OO'), $(c g11rfin_rig_extreme_front extreme), $(c g11rfin_rig_frown_front frown)" "$(c g11rfin_lod_lod0_front 'LOD0'), $(c g11rfin_lod_lod2_front 'LOD2'), $(c g11rfin_lod_lod3_front 'LOD3'), $(c g11rfin_mot_turn06_3q 'turn 0.6s'), $(c g11rfin_mot_turn12_front 'turn 1.2s'), $(c g11rfin_mot_stop06_3q 'run-stop'), $F/g11rafter_hair_F.png|after restart, $F/g11rafter_hair_C.png|after restart 3q"
echo BOARDS_DONE
